### ISSUE TITLE
Different memory consumption among GPUs

### ISSUE THREAD

**Issue by jasonliu747** [bytedance/byteps#278]
**Describe the bug**
When running a training, either on single or multiple nodes, the memory of first GPU card will always be consumed more than others. Looks like it only happened after upgrading BytePS version to v0.2.4.

**To Reproduce**
```
apiVersion: "kubeflow.org/v1beta1"
kind: "MXJob"
metadata:
  name: "byteps-mxnet-job"
spec:
  jobMode: MXTrain
  mxReplicaSpecs:
    Scheduler:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: bytepsimage/mxnet:v0.2.4
              command: ["bpslaunch"]
    Server:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: bytepsimage/mxnet:v0.2.4
              command: ["bpslaunch"]
              resources:
                requests:
                  cpu: 4
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: bytepsimage/mxnet:v0.2.4
              command: ["bpslaunch"]
              args: ["python3", "/usr/local/byteps/example/mxnet/train_imagenet_byteps.py", "--benchmark", "1", "--batch-size=32", "--num-epochs=1"]
              volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              resources:
                limits:
                  nvidia.com/gpu: 8
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24452340/88752517-b7f2f100-d18c-11ea-8729-4dd6102498b9.png)
